# A64 quad core 1GB SoC GBE Wi-Fi/BT
BOARD_NAME="A64-OLinuXino"
BOARDFAMILY="sun50i-olinuxino"
BOOTCONFIG="A64-OLinuXino_defconfig"
#
MODULES_NEXT="g_serial"
CPUMIN="408000"
CPUMAX="1296000"
#
KERNEL_TARGET="next"
CLI_TARGET="stretch:next"
DESKTOP_TARGET="bionic:next"
#
CLI_BETA_TARGET=""
DESKTOP_BETA_TARGET=""
